# Generated by Django 4.1.3 on 2023-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="new",
            name="top_in_category",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="new",
            name="top_new",
            field=models.BooleanField(default=False),
        ),
    ]
